### ISSUE TITLE
Resolver.bintrayRepo("buildo", "maven") is missing

### ISSUE THREAD

**Issue by calippo** [buildo/sbt-buildo#1]
## story
- as a user of the plugin I don't want to remember to include buildo-maven  in the resolvers list so that I don't waste time.
## description

Either embed Resolver.bintrayRepo("buildo", "maven") or include it in the readme.md e.g.

```
inThisBuild(Seq(
  name := "nozzletest",
  resolvers += Resolver.bintrayRepo("buildo", "maven"),
  libraryDependencies ++= defaultDependencies
))
```

**Comment by gabro** [comment]
right, the real question is, why aren't all our libraries linked to JCenter? I'll investigate. In the meantime, we can add the resolver to this plugin.
